/* The following code was generated by JFlex 1.4.2 on 20:35 17/11/08 */

package ic.parser;

import java.io.IOException;
import java.io.Reader;
import java.util.Collection;

public class Scanner {

    public void process(Reader rd, Collection<Token> tokens)
            throws LexicalError, IOException {
        Token token;
        Lexer lexer = new Lexer(rd);

        while ((token = lexer.yylex()) != null)
            tokens.add(token);
    }

}